#This is a sample Image 
FROM ubuntu 
MAINTAINER tzamalis@ceid.upatras.gr

RUN apt-get update
RUN apt-get -y install apt-utils
RUN apt-get -y install curl
RUN apt-get -y install nginx
# CMD ["nginx", "-g", "daemon off;"]
CMD [“echo”,”Image created”]